name: navigator
tile_size: 0.6
origin_x: 0.0
origin_z: 0.0
default_spawn: n_8_4
default_start: n_8_6
default_goal: n_2_3
nodes:
- id: n_0_0
  label: (0,0)
  col: 0
  row: 0
  x: 0.3
  z: 0.3
  type: curve
  spawn_rot: 3
- id: n_1_0
  label: (1,0)
  col: 0
  row: 1
  x: 0.3
  z: 0.9
  type: curve
  spawn_rot: 3
- id: n_1_1
  label: (1,1)
  col: 1
  row: 1
  x: 0.9
  z: 0.9
  type: curve
  spawn_rot: 3
- id: n_0_3
  label: (0,3)
  col: 3
  row: 0
  x: 2.1
  z: 0.3
  type: cross3
  spawn_rot: 3
- id: n_0_6
  label: (0,6)
  col: 6
  row: 0
  x: 3.9
  z: 0.3
  type: curve
  spawn_rot: 3
- id: n_4_6
  label: (4,6)
  col: 6
  row: 4
  x: 3.9
  z: 2.7
  type: cross3
  spawn_rot: 3
- id: n_8_6
  label: (8,6)
  col: 6
  row: 8
  x: 3.9
  z: 5.1
  type: curve
  spawn_rot: 3
- id: n_4_1
  label: (4,1)
  col: 1
  row: 4
  x: 0.9
  z: 2.7
  type: curve
  spawn_rot: 3
- id: n_4_4
  label: (4,4)
  col: 4
  row: 4
  x: 2.7
  z: 2.7
  type: cross4
  spawn_rot: 3
- id: n_2_3
  label: (2,3)
  col: 3
  row: 2
  x: 2.1
  z: 1.5
  type: curve
  spawn_rot: 3
- id: n_2_4
  label: (2,4)
  col: 4
  row: 2
  x: 2.7
  z: 1.5
  type: curve
  spawn_rot: 3
- id: n_8_4
  label: (8,4)
  col: 4
  row: 8
  x: 2.7
  z: 5.1
  type: curve
  spawn_rot: 2


edges:
- from: n_0_0
  to: n_1_0
  distance: 0.6
- from: n_1_0
  to: n_1_1
  distance: 0.6
- from: n_1_1
  to: n_4_1
  distance: 1.8
- from: n_0_0
  to: n_0_3
  distance: 1.8
- from: n_0_3
  to: n_0_6
  distance: 1.8
- from: n_0_6
  to: n_4_6
  distance: 2.4
- from: n_4_6
  to: n_8_6
  distance: 2.4
- from: n_8_6
  to: n_8_4
  distance: 1.2
- from: n_8_4
  to: n_4_4
  distance: 2.4
- from: n_4_4
  to: n_4_1
  distance: 1.8
- from: n_4_4
  to: n_4_6
  distance: 1.2
- from: n_4_4
  to: n_2_4
  distance: 1.2
- from: n_2_4
  to: n_2_3
  distance: 0.6
- from: n_2_3
  to: n_0_3
  distance: 1.2